### ISSUE TITLE
Warning: class_implements(): Class EntityAPIController does not exist....

### ISSUE THREAD

**Issue by bobchristenson** [backdrop-contrib/field_collection#1]
I get a bunch of errors that EntityAPIController does not exist and I tracked them down to field_collection.  See field_collection_entity_info()

Similar issue I ran across with suggested solution for paragraphs module posted here: https://github.com/jacksinn/backdrop-paragraphs/issues/1

**Comment by oadaeh** [comment]
Thanks for creating this issue and pointing to that other issue.
I actually already ran into the problem and fixed it by changing the controller class the entity is based on to EntityDatabaseStorageController, which seems to have fixed it, but then I ran into other errors.
However, I'll check into that solution you posted to see if it's a better way forward.

**Comment by oadaeh** [comment]
I've committed a fix for this (and several other things).
