### ISSUE TITLE
Host entity cache clearing should not use nid as the cache ID

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/field_collection#11]
Currently, after this [commit](https://github.com/backdrop-contrib/field_collection/commit/f271886d018bd47e6eeb9b33fee1abacf30fb43e), the host entity cache is cleared after a field is inserted or updated. The new code uses the `nid` of the host entity to clear its entity cache - but the problem is that if the field collection is attached to a different entity type (e.g. the user entity), this will fail.

**Comment by argiepiano** [comment]
PR #12 ready for review and testing.

**Comment by oadaeh** [comment]
Thanks for this. I've merged it in. However, there is a bigger issue in that the Field Collection fields do not show up on users, so it doesn't really matter if the cache is being cleared or not. :/
