### ISSUE TITLE
User entities do not display Field Collection fields

### ISSUE THREAD

**Issue by oadaeh** [backdrop-contrib/field_collection#13]
I witnessed this while testing #12, but I didn't get into the details to figure out what was actually happening.

**Comment by argiepiano** [comment]
The do show up both in the user edit form, and in the user create form. You just need to remember to mark the collection as "Display in user registration form". See below.

<img width="734" alt="Screen Shot 2023-07-25 at 9 43 33 PM" src="https://github.com/backdrop-contrib/field_collection/assets/9938978/fb9fea7b-6ca0-4079-b4e0-2ba8291f283a">

**Comment by argiepiano** [comment]
This is what it looks like in the user create form. The collection is called "my collection"

<img width="633" alt="Screen Shot 2023-07-25 at 9 47 35 PM" src="https://github.com/backdrop-contrib/field_collection/assets/9938978/a52e2200-0ada-4e8c-853e-afdb80f60654">

And this is what it looks like in the user edit form
<img width="655" alt="Screen Shot 2023-07-25 at 9 48 02 PM" src="https://github.com/backdrop-contrib/field_collection/assets/9938978/543a2798-5cdf-49ed-9999-624b0d379847">

**Comment by oadaeh** [comment]
Hmm. It might be time to rebuild my test site.

**Comment by oadaeh** [comment]
I'm closing this.
