### ISSUE TITLE
Update to use hook_path_info() instead of hook_pathauto()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/field_collection#14]
`hook_path_auto()` should be used instead of `hook_pathauto()` and rename the file to `field_collection.path.inc`, similar to how it is with `taxonomy.path.inc`, etc.

Looks like the settings keys have changed slightly: `patterndescr` to `pattern_description` and `patternitems` to `pattern_items`.

**Comment by argiepiano** [comment]
> hook_path_auto() should be used instead of hook_pathauto()

Did you mean `hook_path_info()` rather than `hook_pathauto()`? 

> Looks like the settings keys have changed slightly: patterndescr to pattern_description and patternitems to pattern_items.

I believe those new keys don't use underscores. `pattern description` and `pattern items` with spaces.

**Comment by oadaeh** [comment]
I added the necessary code changes for this and merged them in.

An interesting note is that the relevant change request uses this module as its example, despite the fact this module was ported years later: https://docs.backdropcms.org/change-records/hook_pathauto-replaced-by-hook_path_info
