### ISSUE TITLE
Use public $langcode instead of protected

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/field_collection#15]
Backdrop entities (see `Node`, `File`, `User`, etc) use `public $langcode;`. Field Collection, instead uses `protected $langcode;`. 

This is producing fatal problems for contrib modules that try to access langcode directly, as in `$entity->langcode`. See [this issue](https://github.com/backdrop-contrib/pdf_to_image/issues/9).

It seems unusual that langcode is protected. This is most likely inherited from D7, where $langcode was not a property of Entity API's `Entity`, and where the tables used the column name `language` instead of `langcode`.

**Comment by laryn** [comment]
I ran into this while testing [Field Collection Feeds](https://github.com/backdrop-contrib/field_collection_feeds) and making $langcode public solves the fatal error.

I added a PR.
