### ISSUE TITLE
Get functional tests running

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/field_collection#18]
... and run them via GitHub Action on PRs.

**Comment by indigoxela** [comment]
I did what I could to get them running.
And I did have to fix some details in field_collection.entity.inc, field_collection.module and field_collection.pages.inc to get them running.

4 tests still fail and they seem to fail rightly - something with host cloning and revisions and fields seems fishy, but I'm not planning to spend more time on those - I'm not familiar enough with the module to decide, which changes are appropriate to fix the bugs.

Anyway, here's a PR #19 for your kind review @oadaeh 

The GHA should run on PR, but doesn't do that, yet, as I'm not admin of this repo - it requires merge before the action runs.
But tests can get run locally, already.

**Comment by argiepiano** [comment]
Ive run the tests locally after looking at the code (which looks fine). I'm getting failures on the following lines (are these the same you got?)

- Field collection test: lines 411, 421 and 430
- Field collection content translation: line 667

I looked at 411, 421 and 430. In D7, when you cloned or resaved a node, the field collection field value changed to match the new nid. This is not happening in Backdrop. I haven't looked into why.

**Comment by argiepiano** [comment]
Here are some clues for the failure of lines 411, 421 and 430. 

-`field_collection_field_insert()` checks that the host entity `is_new` flag is set. 
- In D7, when the process reaches `field_collection_field_insert` after saving the cloned nodes, `is_new` is still true. In Backdrop it is not.
- `is_new` is effectively **unset** in [line 477](https://github.com/backdrop/backdrop/blob/a34ee61471f0c6561a89f1237e20b7ce47dac2e2/core/modules/node/node.entity.inc#L477) in Backdrop **before** any hook is invoked (bummer - I've seen this before and I've struggled with this decision to unset it). In D7, `is_new` is unset AFTER invoking all hooks (see [this line](https://git.drupalcode.org/project/drupal/-/blob/7.x/modules/node/node.module?ref_type=heads#L1187))

Given this discrepancy, we should look for another way to check that the host entity was "new" when saved. Not sure how (it's late and I'm tired 😄 )

**Comment by indigoxela** [comment]
> is_new is effectively unset in line 477 in Backdrop before any hook is invoked...

Oh, shoot.

Yes, the same tests fail here locally - the cloning problem.

**Comment by indigoxela** [comment]
HA! Using an additional criterion for node entities specifically gets all tests passing.

I saw that $entity->original is only set if it's not new. A few lines before the property is_new is unset. So in case of node, I use that one to check if the node is new.
Other entity types should behave properly, as in EntityDatabaseStorageController::save the property is removed *after* running the hook.

@argiepiano did I get that correctly in my latest commit?
And yet another time: thank you so much for your valuable help. :pray:

**Comment by argiepiano** [comment]
Thanks, @indigoxela. That approach seems fine to me and it works, so this is good to go - although AFAIK all updated entities will contain the `original` property, so it may be easier just to check for its existence rather than `isNew()` in the original if statement in `field_collection_field_insert`. 

Incidentally, I looked at `EntityPlusController::save()` (which is used by some legacy custom entities like `registration` and all my custom entities in my systems), and it keeps the D7 pattern of removing `is_new` after the hooks run. It also sets `original` as expected, so they would still work with the approach of check if `original` exists in  `field_collection_field_insert`.

**Comment by indigoxela** [comment]
> AFAIK all updated entities will contain the original property...

Interesting - I wasn't sure about that. It doesn't seem to be a required property, at least, as far as I can tell.
That means, we wouldn't have to special-case Node in hook_field_insert... :thinking:

**Comment by indigoxela** [comment]
After some head scratching I decided to stick with the special case for node. I leave it to the maintainer - @oadaeh - to decide whether switching to check for the "original" property (instead of is_new) for all host entities should be the default in that hook implementation.

**Comment by argiepiano** [comment]
> After some head scratching I decided to stick with the special case for node

That works fine!

**Comment by oadaeh** [comment]
The codes seems fine to me and works locally, so I've merged it.
Thank you @indigoxela.
I'm going to submit another change to see if the tests run automatically.
