### ISSUE TITLE
Move entity_revision_load to entity_plus_revision_load

### ISSUE THREAD

**Issue by darby3** [backdrop-contrib/field_collection#2]
There may be other functions moved to entity_plus, but this one jumped out at me.

**Comment by oadaeh** [comment]
I've made lots of changes locally to get this module working in Backdrop, maybe even that one (but I'll check), but I'm still having some odd behaviors saving the field collections. I'll try to get what I've got so far pushed up tonight.

**Comment by oadaeh** [comment]
Yep, I already had them in there. I just pushed my changes up, so you can access where it currently is.
Thanks for the PR, though.
