### ISSUE TITLE
Notice: Undefined index: pattern label in path_patterns_form() on admin/config/urls/path/patterns

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/field_collection#21]
To reproduce:

- Go to admin/config/urls/path/patterns with error display turned on

```
Notice: Undefined index: pattern label in path_patterns_form() (line 388 of .../core/modules/path/path.admin.inc).
```

This is caused by field_collection. At that point (in function path_patterns_form), `$path_info` looks like that:
```
array (
  'entity type' => 'field_collection',
  'token_type' => 'field_collection_item',
  'label' => 'Field collection item paths',
  'pattern description' => 'Default path pattern (applies to all field collections with blank patterns below)',
  'pattern default' => '',
  'pattern items' => 
  array (
    'field_collie' => 'Pattern for all field collection field_collie paths',
  ),
  'type delete callback' => '',
  'batch update callback' => '',
  'batch file' => '',
  'module' => 'field_collection',
  'batch file path' => 'modules/field_collection',
)
```
But no `$path_info['pattern label']`.

So this is possibly a follow up to Issue #14

See also https://docs.backdropcms.org/api/backdrop/core%21modules%21path%21path.api.php/function/hook_path_info/1

**Comment by indigoxela** [comment]
Here's a PR for your review @oadaeh #22 
The 'pattern label' key was added to the return array in Backdrop 1.26.2.

**Comment by indigoxela** [comment]
@oadaeh friendly reminder, that there's still a simple little bug fix PR waiting for review.

**Comment by oadaeh** [comment]
Thanks for reporting this and providing a fix - I've merged it in.
