### ISSUE TITLE
 Call to undefined function entity_language() 

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/field_collection#5]
Using the edit link on a field colleciton item throws this error:
```
Error: Call to undefined function entity_language() in field_collection_item_form() (line 36 of backdrop/docroot/modules/contrib/field_collection/field_collection.pages.inc). 
```

I tried replacing it with the simple `$field_collection_item->langcode;`, but then I got

```
Error: Cannot access protected property FieldCollectionItemEntity::$langcode in field_collection_item_form() (line 36 of backdrop/docroot/modules/contrib/field_collection/field_collection.pages.inc). 
```

**Comment by oadaeh** [comment]
I'm pretty sure I took care of all those, and line 36 of field_collection.pages.inc is empty: https://github.com/backdrop-contrib/field_collection/blob/211f9fee57cc8c1fedb745219f72148e5cc9c448/field_collection.pages.inc#L36
Are you using the latest code?

**Comment by jenlampton** [comment]
> Are you using the latest code?

No, I wasn't. Updated to head and this is not an issue! closing. (and sorry for the noise)

**Comment by oadaeh** [comment]
It's okay. Thanks for the update.
