### ISSUE TITLE
Fields in collections will not save data

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/field_collection#7]
I think fields in field collections aren't properly saving their data. 

Steps to reproduce: (on a fresh backdrop install)
1) Add a field collection to a post
2) add a test field (text, short) to the collection
3) add or edit a post, add a value, save
4) see that there is no value displaying on the post
5) edit the post
6) see that there is no default value in the field either

**Comment by kraslin** [comment]
I've been picking at this on and off the last couple weeks myself:

- It _is_ saving, it's just not clearing the host entity from the cache
- Clearing caches will make the collections appear as expected
- Submitting, then editing and submitting again without clearing in between will lead to data loss (and possibly orphan data in the database as the fields are being saved)

**Comment by oadaeh** [comment]
I just committed some changes that clears the cache of the host entity when a Field Collection item is added or updated.
I also modified the code that sets the cache_entity_field_collection_item table to just do it, since that's default behavior now, but an update will need to be run for that to work.
Try saving with the new code changes and see if it works for you now.

**Comment by herbdool** [comment]
I did a fresh install and fields in collections are saving fine for me. So your recent fix @oadaeh seems to have worked.

**Comment by argiepiano** [comment]
Please see my comment in the [commit](https://github.com/backdrop-contrib/field_collection/commit/f271886d018bd47e6eeb9b33fee1abacf30fb43e). The cache clearing assumes the host entity is a node and is using `nid` to clear the entity cache.

**Comment by herbdool** [comment]
Good point @argiepiano

**Comment by argiepiano** [comment]
PR #12 ready for review and testing (related to issue #11)

**Comment by oadaeh** [comment]
Thanks for the feedback. I've merged in @argiepiano's PR, so I'm going to mark this as fixed.
